services:
  web:
    container_name: customer_orders_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/backend
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: customer_orders_db
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
